### ISSUE TITLE
get error when trying a minimal test using CRA

### ISSUE THREAD

**Issue by asharafshahi** [tigranbs/reactive-qr#3]
Failed to compile.

./node_modules/reactive-qr/dist/index.js
Attempted import error: './qr_decode.worker' does not contain a default export (imported as 'QRWorker').

**Comment by freddiehonohan** [comment]
Also getting this :~/

**Comment by Nasaakaa** [comment]
@tigranbs any answers?

**Comment by tigranbs** [comment]
@Nasaakaa thanks for pushing on this, have tried today on my other environments, I've been able to get it working without issues, however, added console logs on main `onInit` and `onCode` events for a demo, just to see if your browser handles WEBRTC or not.

Also for `qr_decode.worker` @asharafshahi it shouldn't contain any exports, because the final built file is just a Service Worker which loads up within browser, you just need to import it would assigning to a variable (it is already done inside).

Please try also running `HTTPS=true npm start` to make sure you have present HTTPS, because for browser it is important to be under `localhost or with https` in order to access WebRTC features.

**Comment by Nasaakaa** [comment]
Thank you for your reply.

Yeah, I see. It's successfully working. I am very appreciated @tigranbs.

**Comment by hasanzia1993** [comment]
using with/without `HTTPS=true npm start`, tried on localhost
but still getting same error `64:27-35 "export 'default' (imported as 'QRWorker') was not found in './qr_decode.worker'`
